version: '3'
services:
  db:
    image: mongo
    volumes:
      - ./MongoDB:/data/db
    ports:
      - "27017:27017"
    
  nlu_server_app:
    build: ./NLUServer_app
    volumes:
      - ./NLUServer_app:/usr/src/app
      - ./config.ini:/usr/src/app/config.ini
    ports:
      - "12345:12345"
    depends_on:
      - db

  osrm_server_app:
    image: osrm/osrm-backend
    volumes:
      - ./OSRM_server:/data
    ports:
      - "5000:5000"
