version: '3'
services:
  db:
    image: mongo
    volumes:
      - ./MongoDB:/data/db
    ports:
      - "27017:27017"
    
  nlu_server_app:
    build: ./NLUServer_app
    volumes:
      - ./NLUServer_app:/usr/src/app
      - ./config.ini:/usr/src/app/config.ini
    ports:
      - "12345:12345"
    depends_on:
      - db

  redis:
    image: "redislabs/redisgraph:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./redis_data:/data:rw"
  insight:
    image: "redislabs/redisinsight:latest"
    depends_on:
      - redis
    volumes:
      - "./redis_insight_db:/db:rw"
    ports:
      - "8001:8001"